### PR TITLE
Fix: Autoloading is all the bootstrapping required

### PR DESCRIPTION
**Pull request by localheinz**
At least at the moment, so there's not really a need for a file that just includes Composer's autoloading file.

### CODE REVIEW

**Comment by mfrost503** [comment]
This is interesting, I have to admit I'd never seen it done this way...makes perfect sense though.

**Comment by localheinz** [comment]
:+1:

Thank your for accepting all of my changes, Matt!

**Comment by mfrost503** [comment]
Any time! Great PRs, thank you for taking the time to create them!

**Comment by localheinz** [comment]
I consider it mostly fun, so no worries!

**Pull request merged**
